### ISSUE TITLE
Ninetails v2.0.0 build for Windows x64

### ISSUE THREAD

**Issue by CocoTheMii** [MystPi/ninetails#10]
I've built v2.0.0 of Ninetails for x64 versions of Windows.
https://github.com/CocoTheMii/miscellaneous/releases/tag/v1

Built and tested on an Intel Core i7-6600U running Windows 11 build 22000.348; seems to run just fine.
![image](https://user-images.githubusercontent.com/44563370/145660259-ad05c956-9f25-4d99-867c-c823f69e0327.png)

**Comment by MystPi** [comment]
Thank you for contributing! I'll add this to the releases page. 😸

**Comment by MystPi** [comment]
Would you mind building a release for version 2.1.0? It would be quite helpful! Don't feel like you have to, though; it's totally up to you.

**Comment by CocoTheMii** [comment]
Absolutely! I've updated the [release page](https://github.com/CocoTheMii/miscellaneous/releases/tag/v1) to contain a build of 2.1.0.

Built on the same computer as before, using Windows 10 build 19044.1288. I'm currently trying out Kubuntu on my main laptop, so I'm using a VM for Windows stuff.
![image](https://user-images.githubusercontent.com/44563370/145744879-1b342e65-5f6d-499d-83f1-cc820d9de8b8.png)

**Comment by MystPi** [comment]
Wow, thank you!
