### ISSUE TITLE
Please, we need updates

### ISSUE THREAD

**Issue by Lynph27** [MystPi/ninetails#130]
Please, update browser, your project really good)
![image](https://user-images.githubusercontent.com/100804832/161234899-59c2e5e4-3168-4f47-a8b9-5d60331aa2ee.png)
Please add russian language
![image](https://user-images.githubusercontent.com/100804832/161235217-64b00085-9971-4ffc-b019-db1e946dad34.png)
add dark theme browser and more actions with tabs, make it more convenient

**Comment by MystPi** [comment]
Thanks for your feedback, your additions will be considered. 😸
