### ISSUE TITLE
Downloads manager

### ISSUE THREAD

**Issue by JoshAtticus** [MystPi/ninetails#146]
Can we get a download manager for ninetails? That would really help with making it even more useful.

**Comment by MystPi** [comment]
Ninetails can already download files.

**Comment by JoshAtticus** [comment]
> Ninetails can already download files.

It doesn't have a download manager though, for viewing download progress, copying link, pausing, cancelling etc

**Comment by MystPi** [comment]
That looks like a bit over my skillset. Also, since I chose to use the webview tag for Ninetails, its capabilities are pretty limited unfortunately. I would love to rewrite Ninetails in React...

**Comment by JoshAtticus** [comment]
Dang, that sucks. Hopefully in the future it'll become possible, also, is it possible to get a "Open in new tab" and "Open in new window" feature for right click? I use that feature very often when browsing and it's becoming annoying not having it in Ninetails

**Comment by MystPi** [comment]
You can middle click a link to open it in a new tab.

**Comment by JoshAtticus** [comment]
> You can middle click a link to open it in a new tab.

Thanks!

**Comment by MystPi** [comment]
No problem.
