### ISSUE TITLE
Search Engine.

### ISSUE THREAD

**Issue by Darth-Ness** [MystPi/ninetails#16]
Yes, I know Google has a ridiculous amount of the market but as long as the market share isn't 100%. Then there should be an option for a search engine. 
Plus, you can't call yourself a privacy browser with Google as the default and the only option.

**Comment by webdev03** [comment]
I think this is a work in progress

**Comment by MystPi** [comment]
Yup, I [plan](https://github.com/MystPi/ninetails/projects/1#card-74615110) to add that eventually.

**Comment by MystPi** [comment]
Completed in version 2.2.0.
