### ISSUE TITLE
macOS Intel 64-bit 2.1.0 release!

### ISSUE THREAD

**Issue by webdev03** [MystPi/ninetails#21]
Here's 2.1.0 for you 😄 https://github.com/webdev03/webdev03/releases/download/v1/Ninetails-darwin-x64-2.1.0.zip

**Comment by webdev03** [comment]
Too many tabs can make Ninetails crash by the way

**Comment by MystPi** [comment]
Thank you for your build!

> Too many tabs can make Ninetails crash by the way

That would probably happen with any browser. 😸

**Comment by webdev03** [comment]
No, I mean, the firefox installation I am using right now can handle more than 30 tabs, while a similar amount on Ninetails just makes Ninetails quit and crash.
