### ISSUE TITLE
Ubuntu/Debian x86_64 build :)

### ISSUE THREAD

**Issue by JaydenDev** [MystPi/ninetails#26]
bonus: rpm64

uhh... how do i attach files...?

**Comment by hello-smile6** [comment]
Just upload them to https://instant.io/ and share the link. Leave the tab open.

**Comment by JaydenDev** [comment]
uploading them to my DL server.

**Comment by hello-smile6** [comment]
> uploading them to my DL server.

Why not instant.io ? It's faster, and Replit only allows so much storage.

**Comment by JaydenDev** [comment]
instant.io doesn't support ZIP, DEB, Or RPM

**Comment by JaydenDev** [comment]
i give up

**Comment by hello-smile6** [comment]
> instant.io doesn't support ZIP, DEB, Or RPM

Yes, it does. It's a browser torrent client. Just share anything.

**Comment by hello-smile6** [comment]
> So where are the files? Also is this for version 2.1.0?

IDK, check https://replit.com/JaydenDev/dl

**Comment by hello-smile6** [comment]
@MystPi Found them, https://dl.jaydendev.repl.co/ninetails
