### ISSUE TITLE
Ninetails Windows x64 build

### ISSUE THREAD

**Issue by kccuber-scratch** [MystPi/ninetails#3]
Here's a Ninetails build for Windows x64:
https://github.com/kccuber-scratch/kccuber-scratch.github.io/raw/main/Ninetails-1.0.0%20Setup.zip
The .exe is inside the zip file

**Comment by MystPi** [comment]
Thanks for contributing! I'll add this to the releases tomorrow.

**Comment by kccuber-scratch** [comment]
> Thanks for contributing! I'll add this to the releases tomorrow.

It's already tomorrow and I don't see it

**Comment by MystPi** [comment]
> > Thanks for contributing! I'll add this to the releases tomorrow.
> 
> It's already tomorrow and I don't see it

Sorry, I haven't gotten around to it yet.
