### ISSUE TITLE
Update notification shows when up-to-date

### ISSUE THREAD

**Issue by hello-smile6** [MystPi/ninetails#31]
Is this a problem? I am on `main`.

**Comment by webdev03** [comment]
I think my PR fixes it.

**Comment by hello-smile6** [comment]
> I think my PR fixes it.

Okay. By the way, https://github.com/MystPi/dreamcss and https://github.com/MystPi/bridge are amazing.

**Comment by MystPi** [comment]
Fixed. Version 2.2.0 will make it even better, thanks to @webdev03.
