### ISSUE TITLE
Crashes when domain with invalid cert is opened

### ISSUE THREAD

**Issue by hello-smile6** [MystPi/ninetails#32]
I only managed to reproduce this once, with my school's domain name. However, it crashes.

**Comment by ninjamar** [comment]
Any websites we can test this on?

**Comment by MystPi** [comment]
Please provide reproduction steps when creating an issue.

**Comment by hello-smile6** [comment]
Try [badssl.com](https://badssl.com/) subdomains.

**Comment by ninjamar** [comment]
For me, the page is just blank when on self-signed

**Comment by hello-smile6** [comment]
> For me, the page is just blank when on self-signed

It was `NET::ERR_CERT_COMMON_NAME_INVALID` in Chromium.

**Comment by ninjamar** [comment]
> > For me, the page is just blank when on self-signed
> 
> It was `NET::ERR_CERT_COMMON_NAME_INVALID` in Chromium.

I'm talking about this in ninetails. I think ninetails just ignores the issue and renders the page.

**Comment by hello-smile6** [comment]
> > > For me, the page is just blank when on self-signed
> > 
> > 
> > It was `NET::ERR_CERT_COMMON_NAME_INVALID` in Chromium.
> 
> I'm talking about this in ninetails. I think ninetails just ignores the issue and renders the page.

Well, it crashed once.

**Comment by MystPi** [comment]
I tested most of the https://badssl.com subdomains in Ninetails, and none of them made it crash.

**Comment by hello-smile6** [comment]
@MystPi Try with an x64 Windows 10 VM and a clean install. It only happens when it first opens one.
