### ISSUE TITLE
`window.open` and `prompt` seem buggy

### ISSUE THREAD

**Issue by hello-smile6** [MystPi/ninetails#33]
Trying `prompt()` using sheeptester.github.io/hello-world/questionmarkquestionmarkquestionmark.html (@SheepTester Yes, I still use that) doesn't work.

**Comment by Mbrick2** [comment]
https://stackoverflow.com/questions/38858879/replace-prompt-in-on-electron

**Comment by MystPi** [comment]
I'm not sure that this will be easy to fix.

**Comment by MystPi** [comment]
Also `window.open` should work by opening a new tab.

**Comment by ninjamar** [comment]
> I'm not sure that this will be easy to fix.

We could inject a script that will override prompt.

**Comment by hello-smile6** [comment]
> > I'm not sure that this will be easy to fix.
> 
> We could inject a script that will override prompt.

What about using that macos prompt replacement?

**Comment by MystPi** [comment]
> > I'm not sure that this will be easy to fix.
> 
> We could inject a script that will override prompt.

Yes, that would be possible.

**Comment by hello-smile6** [comment]
> > > I'm not sure that this will be easy to fix.
> > 
> > 
> > We could inject a script that will override prompt.
> 
> Yes, that would be possible.

How would I make https://github.com/MystPi/dreamcss support inputs?

**Comment by ninjamar** [comment]
> > > I'm not sure that this will be easy to fix.
> > 
> > 
> > We could inject a script that will override prompt.
> 
> What about using that macos prompt replacement?

Ninetails wouldn't be cross-platform.

**Comment by hello-smile6** [comment]
> > > > I'm not sure that this will be easy to fix.
> > > 
> > > 
> > > We could inject a script that will override prompt.
> > 
> > 
> > What about using that macos prompt replacement?
> 
> Ninetails wouldn't be cross-platform

If that prompt replacement is cross-platform, it would be. Or we could send native notifications.

**Comment by ninjamar** [comment]
> If that prompt replacement is cross-platform, it would be. Or we could send native notifications.

True

**Comment by hello-smile6** [comment]
> > If that prompt replacement is cross-platform, it would be. Or we could send native notifications.
> 
> True

However, there's still the risk of denial-of-service attacks.

**Comment by ninjamar** [comment]
> > > If that prompt replacement is cross-platform, it would be. Or we could send native notifications.
> > 
> > 
> > True
> 
> However, there's still the risk of denial-of-service attacks.

wdym?

**Comment by hello-smile6** [comment]
> > > > If that prompt replacement is cross-platform, it would be. Or we could send native notifications.
> > > 
> > > 
> > > True
> > 
> > 
> > However, there's still the risk of denial-of-service attacks.
> 
> wdym?

```javascript
document.onclick=function() {
  setInterval(function() {
    window.open("about:blank").alert(JSON.stringify(new Array(10000).fill("a")));
  },1);
}
```
Does that explain it? It could take down the main process with just opening lots of tabs.

**Comment by ninjamar** [comment]
> > > > > If that prompt replacement is cross-platform, it would be. Or we could send native notifications.
> > > > 
> > > > 
> > > > True
> > > 
> > > 
> > > However, there's still the risk of denial-of-service attacks.
> > 
> > 
> > wdym?
> 
> ```js
> document.onclick=function() {
>   setInterval(function() {
>     window.open("about:blank").alert(JSON.stringify(new Array(10000).fill("a")));
>   },1);
> }
> ```
> 
> Does that explain it? It could take down the main process with just opening lots of tabs.

isn't there dos for any prompt then?

**Comment by hello-smile6** [comment]
> > > > > > If that prompt replacement is cross-platform, it would be. Or we could send native notifications.
> > > > > 
> > > > > 
> > > > > True
> > > > 
> > > > 
> > > > However, there's still the risk of denial-of-service attacks.
> > > 
> > > 
> > > wdym?
> > 
> > 
> > ```js
> > document.onclick=function() {
> >   setInterval(function() {
> >     window.open("about:blank").alert(JSON.stringify(new Array(10000).fill("a")));
> >   },1);
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Does that explain it? It could take down the main process with just opening lots of tabs.
> 
> isn't there dos for any prompt then?

Well, since Freecat uses HTML for the tabs UI, a malicious website could open a large amount of tabs at once. Normally, the fact that non-focused pages can't open tabs as quickly would help prevent it, but since every tab is prioritized equally, there's nothing keeping a malicious website from crashing the browser.

**Comment by ninjamar** [comment]
> > > > > > > If that prompt replacement is cross-platform, it would be. Or we could send native notifications.
> > > > > > 
> > > > > > 
> > > > > > True
> > > > > 
> > > > > 
> > > > > However, there's still the risk of denial-of-service attacks.
> > > > 
> > > > 
> > > > wdym?
> > > 
> > > 
> > > ```js
> > > document.onclick=function() {
> > >   setInterval(function() {
> > >     window.open("about:blank").alert(JSON.stringify(new Array(10000).fill("a")));
> > >   },1);
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Does that explain it? It could take down the main process with just opening lots of tabs.
> > 
> > 
> > isn't there dos for any prompt then?
> 
> Well, since Freecat uses HTML for the tabs UI, a malicious website could open a large amount of tabs at once. Normally, the fact that non-focused pages can't open tabs as quickly would help prevent it, but since every tab is prioritized equally, there's nothing keeping a malicious website from crashing the browser.

we can add a limit to tabs opened once i finish my userscript thing

**Comment by hello-smile6** [comment]
> > > > > > > > If that prompt replacement is cross-platform, it would be. Or we could send native notifications.
> > > > > > > 
> > > > > > > 
> > > > > > > True
> > > > > > 
> > > > > > 
> > > > > > However, there's still the risk of denial-of-service attacks.
> > > > > 
> > > > > 
> > > > > wdym?
> > > > 
> > > > 
> > > > ```js
> > > > document.onclick=function() {
> > > >   setInterval(function() {
> > > >     window.open("about:blank").alert(JSON.stringify(new Array(10000).fill("a")));
> > > >   },1);
> > > > }
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Does that explain it? It could take down the main process with just opening lots of tabs.
> > > 
> > > 
> > > isn't there dos for any prompt then?
> > 
> > 
> > Well, since Freecat uses HTML for the tabs UI, a malicious website could open a large amount of tabs at once. Normally, the fact that non-focused pages can't open tabs as quickly would help prevent it, but since every tab is prioritized equally, there's nothing keeping a malicious website from crashing the browser.
> 
> we can add a limit to tabs opened once i finish my userscript thing

Or rate-limit it. Maybe even use `requestAnimationFrame` and updating the tabs once per frame.

**Comment by ninjamar** [comment]
> Or rate-limit it. Maybe even use `requestAnimationFrame` and updating the tabs once per frame.
ok

**Comment by MystPi** [comment]
Seems dead. Feel free to comment if there are any breakthroughs.
