### ISSUE TITLE
Idea: Use GitHub Actions for building Ninetails

### ISSUE THREAD

**Issue by webdev03** [MystPi/ninetails#36]
I guess then as soon as a release is made you can instantly build for Windows, macOS and Ubuntu. This might take some time to set up though.

**Comment by ninjamar** [comment]
This would be a good feature.

**Comment by webdev03** [comment]
I don't know if you can specify Intel or M1 though.

**Comment by ninjamar** [comment]
Github doesn't support this yet.
https://github.com/actions/virtual-environments/issues/2187

**Comment by webdev03** [comment]
Oh okay, so M1 builds will need to be manual, but Intel builds can be automatic.

**Comment by ninjamar** [comment]
Yep

**Comment by MystPi** [comment]
Ooh, this is a great idea! I'm not very good at GH actions, so maybe someone else could do it? I know @ninjamar is at least somewhat good with them.

**Comment by ScolderCreations** [comment]
> Ooh, this is a great idea! I'm not very good at GH actions, so maybe someone else could do it? I know @ninjamar is at least somewhat good with them.

I can do it.

**Comment by MystPi** [comment]
> > Ooh, this is a great idea! I'm not very good at GH actions, so maybe someone else could do it? I know ninjamar is at least somewhat good with them.
> 
> I can do it.

I've already started on the build-action branch. It can build it already, I just don't know how to upload the files to a release.

**Comment by webdev03** [comment]
> > > Ooh, this is a great idea! I'm not very good at GH actions, so maybe someone else could do it? I know ninjamar is at least somewhat good with them.
> > 
> > 
> > I can do it.
> 
> I've already started on the build-action branch. It can build it already, I just don't know how to upload the files to a release.

There should be an API to do that...

**Comment by MystPi** [comment]
> > > > Ooh, this is a great idea! I'm not very good at GH actions, so maybe someone else could do it? I know ninjamar is at least somewhat good with them.
> > > 
> > > 
> > > I can do it.
> > 
> > 
> > I've already started on the build-action branch. It can build it already, I just don't know how to upload the files to a release.
> 
> There should be an API to do that...

There is; I'm currently working on it.

**Comment by webdev03** [comment]
OK! :smile:

**Comment by MystPi** [comment]
> @MystPi
> 
> ```yaml
> on: workflow_dispatch
> ```
> 
> might work better than push and pull but then it will be manual, or you can detect when a new tag starting with `v` is made.

I'm doing it when a new release is made. 😺

**Comment by MystPi** [comment]
YES IT'S WORKING! https://github.com/MystPi/ninetails/releases/tag/test

**Comment by MystPi** [comment]
Could you test-install the build to see if it's okay?

**Comment by webdev03** [comment]
Hmm, okay! :smile:

**Comment by webdev03** [comment]
Yes, it works, for some reason the first time I unzipped it, it said the file could not be found, but I unzipped it again, now it works! 🎉

**Comment by MystPi** [comment]
Great!
