### ISSUE TITLE
Ninetails 64 bit DEB package

### ISSUE THREAD

**Issue by JaydenDev** [MystPi/ninetails#4]
available at https://dl.jaydendev.repl.co/ninetails-stable-64.deb

**Comment by MystPi** [comment]
Thank you! Have you tested it completely by installing it?

**Comment by JaydenDev** [comment]
I have not yet, but it should work. I already have ninetails installed, so I can't try it now.

**Comment by MystPi** [comment]
> I have not yet, but it should work. I already have ninetails installed, so I can't try it now.

Fair enough. 😸  It has been added to the releases; thank you for contributing!
