### ISSUE TITLE
[discuss] More customization options.

### ISSUE THREAD

**Issue by MystPi** [MystPi/ninetails#46]
Discuss some more customization options you would like Ninetails to have.

Options:
- [x] Search engine
- [x] Homepage
- [ ] Dark mode

**Comment by hello-smile6** [comment]
I got dark mode covered.

**Comment by JaydenDev** [comment]
customizable size options

for example like Firefox

Normal, Touch, and Compact

**Comment by hello-smile6** [comment]
> customizable size options
> 
> for example like Firefox
> 
> Normal, Touch, and Compact

That'd probably be hard, but I think it'd be possible.

**Comment by dnlnrs** [comment]
I've added the possibility to set a different "homepage"
https://github.com/MystPi/ninetails/pull/51

**Comment by MystPi** [comment]
> I've added the possibility to set a different "homepage" #51

Great idea! I've left a comment describing some changes I would like, then I'll merge.

**Comment by ninjamar** [comment]
I'm trying to help @webdev03 with extensions (#50)

**Comment by JoshAtticus** [comment]
I found a problem with the search engine thing, even when I change it to a valid search engine, the homepage still says Search with Google

**Comment by MystPi** [comment]
> I found a problem with the search engine thing, even when I change it to a valid search engine, the homepage still says Search with Google

You're right. Now it just says 'Search the web...'.

**Comment by JoshAtticus** [comment]
I made heaps of different homepages for Ninetails: https://github.com/JoshAtticus/Ninetails-homepages/

**Comment by hello-smile6** [comment]
@JoshAtticus The domain your certificate uses seems to be a fake cloudflare domain. What???

**Comment by hello-smile6** [comment]
> I made heaps of different homepages for Ninetails: https://github.com/JoshAtticus/Ninetails-homepages/

@MystPi Don't use their thing. https://daniel.is-a.dev/blog/freenom-the-free-domains-website-is-a-scam-3 That's their hosting provider. I'm going to make a copy on replit.

**Comment by JoshAtticus** [comment]
> > I made heaps of different homepages for Ninetails: https://github.com/JoshAtticus/Ninetails-homepages/
> 
> @MystPi Don't use their thing. https://daniel.is-a.dev/blog/freenom-the-free-domains-website-is-a-scam-3 That's their hosting provider. I'm going to make a copy on replit.

I beg your pardon? I use 000webhost and it's trusted, it's not freenom and @MystPi already uses freenom

**Comment by hello-smile6** [comment]
> > > I made heaps of different homepages for Ninetails: https://github.com/JoshAtticus/Ninetails-homepages/
> > 
> > 
> > @MystPi Don't use their thing. https://daniel.is-a.dev/blog/freenom-the-free-domains-website-is-a-scam-3 That's their hosting provider. I'm going to make a copy on replit.
> 
> I beg your pardon? I use 000webhost and it's trusted, it's not freenom and @MystPi already uses freenom

Never mind

**Comment by MystPi** [comment]
It says it's insecure, even if I use http.

**Comment by hello-smile6** [comment]
> It says it's insecure, even if I use http.

Use <a href="https://ninetails-homepages.9pfs.repl.co/">my copy</a>.

**Comment by hello-smile6** [comment]
@MystPi Do you have a Replit account? I need help fixing the homepages site.

**Comment by JoshAtticus** [comment]
> > It says it's insecure, even if I use http.
> 
> Use [my copy](https://ninetails-homepages.9pfs.repl.co/).

Uhm hmm?

**Comment by hello-smile6** [comment]
> > > It says it's insecure, even if I use http.
> > 
> > 
> > Use [my copy](https://ninetails-homepages.9pfs.repl.co/).
> 
> Huh hmmm? Defamation for the services I use?

It supports HTTPS.

**Comment by JoshAtticus** [comment]
> > > > It says it's insecure, even if I use http.
> > > 
> > > 
> > > Use [my copy](https://ninetails-homepages.9pfs.repl.co/).
> > 
> > 
> > Huh hmmm? Defamation for the services I use?
> 
> It supports HTTPS.

So? There isn't really a need, when you type stuff in, it isn't uploading it to analytics or anything like that, let's take the duckduckgo one for example, it redirects to **https**://duckduckgo.com/your-search-query, not an http site, you that search is encrypted using https.

**Comment by hello-smile6** [comment]
> > > > > It says it's insecure, even if I use http.
> > > > 
> > > > 
> > > > Use [my copy](https://ninetails-homepages.9pfs.repl.co/).
> > > 
> > > 
> > > Huh hmmm? Defamation for the services I use?
> > 
> > 
> > It supports HTTPS.
> 
> So? There isn't really a need, when you type stuff in, it isn't uploading it to analytics or anything like that, let's take the duckduckgo one for example, it redirects to **https**://duckduckgo.com/your-search-query, not an http site, you that search is encrypted using https.

Hmm, so what about those hotel ad injection things and stuff like that?
https://www.theverge.com/2012/4/7/2931600/hotel-caught-injecting-advertising-into-web-pages-on-complimentary-wi

**Comment by JoshAtticus** [comment]
> > > > > > It says it's insecure, even if I use http.
> > > > > 
> > > > > 
> > > > > Use [my copy](https://ninetails-homepages.9pfs.repl.co/).
> > > > 
> > > > 
> > > > Huh hmmm? Defamation for the services I use?
> > > 
> > > 
> > > It supports HTTPS.
> > 
> > 
> > So? There isn't really a need, when you type stuff in, it isn't uploading it to analytics or anything like that, let's take the duckduckgo one for example, it redirects to **https**://duckduckgo.com/your-search-query, not an http site, you that search is encrypted using https.
> 
> Hmm, so what about those hotel ad injection things and stuff like that? https://www.theverge.com/2012/4/7/2931600/hotel-caught-injecting-advertising-into-web-pages-on-complimentary-wi

That's possible to pretty much any link

**Comment by MystPi** [comment]
Please stay on topic!

**Comment by JoshAtticus** [comment]
> > It says it's insecure, even if I use http.
> 
> Use [my copy](https://ninetails-homepages.9pfs.repl.co/).

I NEVER consented to you plagiarizing my work and giving me no credit

**Comment by webdev03** [comment]
I can work on Dark Mode like how I did with Catalyst if you would like :smile:

**Comment by MystPi** [comment]
If I do implement dark mode, I'll probably do it myself. Thanks for the offer though! 😸

**Comment by MystPi** [comment]
Kind of dead.
