### ISSUE TITLE
Can't log in to scratch

### ISSUE THREAD

**Issue by JaydenDev** [MystPi/ninetails#5]
When attempting to log into scratch, scratch says an error occurred when the correct email and password is put in.

Potential causes

missing standard components in the web renderer
cookies

**Comment by MystPi** [comment]
It works perfectly for me; maybe it's something on your end?

**Comment by MystPi** [comment]
Sorry, I accidentally closed this.

**Comment by MystPi** [comment]
I'm going to close this for now.

**Comment by JaydenDev** [comment]
All the details i have is just scratch saying an error occurs when I log in, it doesn't let me access dev tools to see the console.

**Comment by JaydenDev** [comment]
screenshot:
![image](https://user-images.githubusercontent.com/92550746/145693238-f4c17ea9-8216-4a6f-b345-e3a599b03abe.png)

**Comment by JaydenDev** [comment]
ss2
(screen shot 2)
![image](https://user-images.githubusercontent.com/92550746/145693326-5a2dda2c-81fc-4cc4-a503-039670dd3f2e.png)

**Comment by JaydenDev** [comment]
some more findings

https://scratch.mit.edu/login on firefox redirects to https://scratch.mit.edu
on ninecat https://scratch.mit.edu/login shows

```
[{"username": "", "num_tries": 0, "success": 0, "msg": "Something went wrong", "messages": [], "id": null}]
```

**Comment by JaydenDev** [comment]
Remember, saying "WoRkS fOr Me" is stupid, i hate it, its stupid.
For an app to be successful it doesn't need to just work for YOU, do you CARE about the USERS!?

**Comment by webdev03** [comment]
> Remember, saying "WoRkS fOr Me" is stupid, i hate it, its stupid. For an app to be successful it doesn't need to just work for YOU.

But if they can't recreate the issue, then how will it be debugged?

**Comment by MystPi** [comment]
> > Remember, saying "WoRkS fOr Me" is stupid, i hate it, its stupid. For an app to be successful it doesn't need to just work for YOU.
> 
> But if they can't recreate the issue, then how will it be debugged?

Exactly!

**Comment by MystPi** [comment]
> All the details i have is just scratch saying an error occurs when I log in, it doesn't let me access dev tools to see the console.

Right click -> inspect.

**Comment by JaydenDev** [comment]
I already showed all the logs and findings I have.
i managed to open the console as well.

**Comment by Quantum-Codes** [comment]
Is there any website for the search engine like chrome has Google.com?
