### ISSUE TITLE
Extensions implementation

### ISSUE THREAD

**Issue by webdev03** [MystPi/ninetails#50]
I think that ninetails should have an implementation of extensions (it just is necessary in a web browser) but the main problem with this is the rules on Scratch that disallow mentioning extensions. If this can be overcome, it would be awesome to have an adblocker on Ninetails!

**Comment by ninjamar** [comment]
I would love to have Scratch Addons on ninetails.

**Comment by webdev03** [comment]
wait so we can mention sa?

**Comment by MystPi** [comment]
> wait so we can mention sa?

I don't think you're supposed to, but I don't care if you do.

**Comment by webdev03** [comment]
WebExtensions would be kind of hard to implement though.

**Comment by ninjamar** [comment]
We could start small with something like userscripts.

**Comment by webdev03** [comment]
Yeah, that would be a good idea. Just something that can be run as normal JS code like it was in the webview.

**Comment by ninjamar** [comment]
How about we can do some script injecting then work out way up to the electron api.

**Comment by ninjamar** [comment]
I'll try to figure out a way to inject scripts inside something.

**Comment by webdev03** [comment]
Okay !

**Comment by ninjamar** [comment]
https://github.com/ninjamar/ninetails
I added the base of an extension loader (it can load from urls) but I am not good at the ui stuff.

**Comment by ninjamar** [comment]
@MystPi  could you help with the ui on my fork?

**Comment by ninjamar** [comment]
I added userstyles and manifests. 
https://github.com/ninjamar/ninetails/blob/main/src/loader.js#L17
https://github.com/ninjamar/ninetails/blob/main/src/loader.js#L25 
^^ Sample manifests

**Comment by MystPi** [comment]
Nice! Please make sure you're using 2 spaces for tabs, instead of 4.

**Comment by MystPi** [comment]
> MystPi could you help with the ui on my fork?

What type of UI do you want for it?

**Comment by MystPi** [comment]
There are actually pre-built functions for injecting styles into a webview. You should probably use it instead, as you can also remove the injected style.

`webview.insertCSS` and `webview.removeInsertedCSS`: https://www.electronjs.org/docs/latest/api/webview-tag#webviewinsertcsscss

**Comment by ninjamar** [comment]
> > MystPi could you help with the ui on my fork?
> 
> What type of UI do you want for it?

Could you add a userscript/userstyle settings page so we can load them by url?

**Comment by ninjamar** [comment]
> There are actually pre-built functions for injecting styles into a webview. You should probably use it instead, as you can also remove the injected style.
> 
> `webview.insertCSS` and `webview.removeInsertedCSS`: https://www.electronjs.org/docs/latest/api/webview-tag#webviewinsertcsscss

I'll do this when I have the chance.

**Comment by MystPi** [comment]
> > There are actually pre-built functions for injecting styles into a webview. You should probably use it instead, as you can also remove the injected style.
> > `webview.insertCSS` and `webview.removeInsertedCSS`: https://www.electronjs.org/docs/latest/api/webview-tag#webviewinsertcsscss
> 
> What about scripts? Should I use `webview.executeJavaScript`?

I don't really know. Possibly?

**Comment by ninjamar** [comment]
> > > There are actually pre-built functions for injecting styles into a webview. You should probably use it instead, as you can also remove the injected style.
> > > `webview.insertCSS` and `webview.removeInsertedCSS`: https://www.electronjs.org/docs/latest/api/webview-tag#webviewinsertcsscss
> > 
> > 
> > What about scripts? Should I use `webview.executeJavaScript`?
> 
> I don't really know. Possibly?

I'll mess around with it.

**Comment by ninjamar** [comment]
Should https be used by default? I'm using https://github.com/MystPi/ninetails/issues/66#issuecomment-997298415 
Should we host the proxy on startup locally?

**Comment by hello-smile6** [comment]
> Should https be used by default? I'm using [#66 (comment)](https://github.com/MystPi/ninetails/issues/66#issuecomment-997298415) Should we host the proxy on startup locally?

Replit only allows HTTPS.

**Comment by webdev03** [comment]
What do you mean by https by default?

**Comment by Mbrick2** [comment]
Maybr an enbedded ad/tracker blocker likr brave

**Comment by ninjamar** [comment]
> Maybr an enbedded ad/tracker blocker likr brave
We should have a userscript/userstyle library

**Comment by hello-smile6** [comment]
> Should https be used by default? I'm using [#66 (comment)](https://github.com/MystPi/ninetails/issues/66#issuecomment-997298415) Should we host the proxy on startup locally?

If you enable nodeIntegration and make sure you're careful with user data, you could use <a href="https://npmjs.com/package/node-fetch/" title="We're no strangers to love
You know the rules and so do I
A full commitment's what I'm thinking of
You wouldn't get this from any other guy
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
We've known each other for so long
Your heart's been aching, but
You're too shy to say it
Inside, we both know what's been going on
We know the game and we're gonna play it
And if you ask me how I'm feeling
Don't tell me you're too blind to see
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
(Ooh, give you up)
(Ooh, give you up)
Never gonna give, never gonna give
(Give you up)
Never gonna give, never gonna give
(Give you up)
We've known each other for so long
Your heart's been aching, but
You're too shy to say it
Inside, we both know what's been going on
We know the game and we're gonna play it
I just wanna tell you how I'm feeling
Gotta make you understand
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you
Never gonna give you up
Never gonna let you down
Never gonna run around and desert you
Never gonna make you cry
Never gonna say goodbye
Never gonna tell a lie and hurt you">`node-fetch`</a>.
BTW, hover your mouse over the node-fetch link.

**Comment by webdev03** [comment]
You can inject CSS and JS into the webview.

**Comment by webdev03** [comment]
Unfortunately you can't get access to the DOM 😭

**Comment by hello-smile6** [comment]
> Unfortunately you can't get access to the DOM 😭

Yes, you can. Just figure out how to run code in the renderer process as the webpage.

**Comment by webdev03** [comment]
That would require giving IPC to the webview right? 😕

**Comment by hello-smile6** [comment]
> Oh right, you can get access to the DOM.

Yep!!!

**Comment by ninjamar** [comment]
> > Should https be used by default? I'm using [#66 (comment)](https://github.com/MystPi/ninetails/issues/66#issuecomment-997298415) Should we host the proxy on startup locally?
> 
> If you enable nodeIntegration and make sure you're careful with user data, you could use [`node-fetch`](https://npmjs.com/package/node-fetch/). BTW, hover your mouse over the node-fetch link.

I don't like the idea of passing untrusted data.

**Comment by ninjamar** [comment]
Can someone help me by testing this branch? it doesn't seem to work. https://github.com/ninjamar/ninetails/tree/broken
I get some error about `GUEST_VIEW_MANAGER_CALL`

**Comment by ninjamar** [comment]
@hello-smile6 @webdev03 can someone help ^^

**Comment by hello-smile6** [comment]
> @hello-smile6 @webdev03 can someone help ^^

Not sure, and haven't even installed NodeJS yet.

**Comment by ninjamar** [comment]
> > @hello-smile6 @webdev03 can someone help ^^
> 
> Not sure, and haven't even installed NodeJS yet.

can you install it ?

**Comment by hello-smile6** [comment]
>

**Comment by hello-smile6** [comment]
> > > @hello-smile6 @webdev03 can someone help ^^
> > 
> > 
> > Not sure, and haven't even installed NodeJS yet.
> 
> can you install it ?

Fine. 🙄 That other comment was accidental. Hit <kbd>Ctrl+Enter</kbd> at the wrong time.

**Comment by webdev03** [comment]
That looks like it should work while I was browsing the code.

**Comment by ninjamar** [comment]
> That looks like it should work while I was browsing the code.

can you check on your computer?
i'm running popos 21.04 , node 17.3.0

**Comment by hello-smile6** [comment]
> > That looks like it should work while I was browsing the code.
> 
> can you check on your computer? i'm running popos 21.04 , node 17.3.0

Just installed nodejs 16.x

**Comment by webdev03** [comment]
You have node 17?? I thought 16 was latest! Lol
You put `./extensions.js` instead of `./js/extensions.js`

**Comment by ninjamar** [comment]
> You have node 17?? I thought 16 was latest! Lol You put `./extensions.js` instead of `./js/extensions.js`

i copy/pasted the files from my computer but i hand did index.html - i fixed it but this wasn't the error i was talking about see the issue comment i made

**Comment by hello-smile6** [comment]
> @hello-smile6 @webdev03 can someone help ^^

Done installing, looking at it

**Comment by ninjamar** [comment]
> > @hello-smile6 @webdev03 can someone help ^^
> 
> Done installing, looking at it

tnx

**Comment by hello-smile6** [comment]
> > > @hello-smile6 @webdev03 can someone help ^^
> > 
> > 
> > Done installing, looking at it
> 
> tnx

Gonna see if I can post from Firefox in a Ubuntu 10 v86 VM first.

**Comment by webdev03** [comment]
I'm working on an implementation in Catalyst right now.

**Comment by hello-smile6** [comment]
> I'm working on an implementation in Catalyst right now.

Nice! Could you by chance work on an Electron v86 client once you get that done? https://copy.sh/v86/

**Comment by ninjamar** [comment]
@hello-smile6  status?

**Comment by webdev03** [comment]
I think that Electron is working on native extensions support, but userscripts we could implement.

**Comment by ninjamar** [comment]
> I think that Electron is working on native extensions support, but userscripts we could implement.

ok - can u review?

**Comment by MystPi** [comment]
> @MystPi can u help?

Sure, what do you need help with?

**Comment by ninjamar** [comment]
> > @MystPi can u help?
> 
> Sure, what do you need help with?

https://github.com/MystPi/ninetails/issues/50#issuecomment-1002730474

**Comment by MystPi** [comment]
Okay, so first you should fetch upstream because you're 40 commits behind. Also you have a syntax error and a reference error:

![image](https://user-images.githubusercontent.com/86574651/149572367-d46d9422-a0c1-4bbf-908c-e97f5568d2cd.png)

**Comment by webdev03** [comment]
bump

**Comment by hello-smile6** [comment]
> bump

So, life is bumpy! 😄

**Comment by MystPi** [comment]
I just found this: https://www.electronjs.org/docs/latest/api/extensions Maybe it will help.

**Comment by hello-smile6** [comment]
> I just found this: https://www.electronjs.org/docs/latest/api/extensions Maybe it will help.

Okay. Sorry if I'm not responding, I'm trying to run an HTTP server on v86 and use ngrok so I can send an HTTP request to it, maybe even dOS a VM, from my browser.

**Comment by webdev03** [comment]
> I just found this: https://www.electronjs.org/docs/latest/api/extensions Maybe it will help.

Would that be able to run in webview?

**Comment by hello-smile6** [comment]
> > I just found this: https://www.electronjs.org/docs/latest/api/extensions Maybe it will help.
> 
> Would that be able to run in webview?

Not sure. Any ideas for ngrok on v86?

**Comment by ninjamar** [comment]
> > I just found this: https://www.electronjs.org/docs/latest/api/extensions Maybe it will help.
> 
> Would that be able to run in webview?

That would work

**Comment by ninjamar** [comment]
I don't have time to do this anymore

**Comment by MystPi** [comment]
Okay.
