### ISSUE TITLE
Move ninetails.cf to github pages

### ISSUE THREAD

**Issue by ninjamar** [MystPi/ninetails#57]
Move ninetails.cf to github pages because most of the stuff is already here.

**Comment by webdev03** [comment]
Maybe move it inside of the browser? But then the auto updating stuff...

**Comment by ninjamar** [comment]
> Maybe move it inside of the browser itself (would work without internet, independent of any hosting)? But then the auto updating stuff...

I personally like github pages better but we could vote on it,

**Comment by MystPi** [comment]
GitHub pages is a good idea, I just don't like the domain mystpi.github.io/Ninetails very much. I suppose it's still better than a Freenom domain, though.

**Comment by MystPi** [comment]
I'll add a custom domain to the GitHub pages site eventually, if I do make it a GH pages site.

**Comment by ninjamar** [comment]
Ok
