### ISSUE TITLE
Enforce Dark Mode on Pages

### ISSUE THREAD

**Issue by JaydenDev** [MystPi/ninetails#59]
An option to apply dark mode to all pages would be nice!

A process called "Inverting Colors" is what is used for this process.
Simply take the CSS of the current page, invert it, and inject it

**Comment by MystPi** [comment]
You can make a PR with this if you want. It would should be added to the settings menu.

**Comment by JaydenDev** [comment]
I don't know how to make a settings menu nor do I know how to inject or Invert CSS

**Comment by MystPi** [comment]
> I don't know how to make or edit a settings menu nor do I know how to inject or Invert CSS

Okay. I don't know how to invert CSS either. 😅

**Comment by JaydenDev** [comment]
Enforced Dark Mode CSS

```css
* {
  color: white;
}

input {
  background-color: white;
  color: black;
}

**Comment by JaydenDev** [comment]
basically view a few websites, find the colors. And find out what colors websites commonly use. Then find an opposite color and have a dark mode css to inject into websites.

**Comment by MystPi** [comment]
It would be easier to execute JavaScript on the page that gives the page dark mode.

**Comment by JaydenDev** [comment]
> It would be easier to execute JavaScript on the page that gives the page dark mode.

Well I suck at JavaScript so I can't do it

**Comment by MystPi** [comment]
Here's some CSS I found on the web: 
```css
:root{
  background-color: #fefefe;
  filter:invert(100%)
}

* {
  background-color: inherit
}

img:not([src*='.svg']), video{
  filter: invert(100%)
}
```

I tested it in Ninetails and it does a pretty good job. I might add this as an option eventually. 😸
