### ISSUE TITLE
macOS Intel build 1.0.0

### ISSUE THREAD

**Issue by webdev03** [MystPi/ninetails#6]
it's in https://github.com/webdev03/webdev03/releases/tag/v1 just so you know
built on a Macbook Air with Intel Core i3 on macOS Monterey 12.0.1

**Comment by MystPi** [comment]
Great, thanks! Have you tested it completely by installing it? If so, I'll add it to the releases tomorrow.

**Comment by webdev03** [comment]
In macOS you don't really "install stuff" (well there is an exception: pkg) but I extracted the ZIP and ran the app, it works well on my device.

**Comment by webdev03** [comment]
<img width="1393" alt="Screen Shot 2021-12-05 at 12 35 29 PM" src="https://user-images.githubusercontent.com/75148774/144727836-ff66bbae-e57c-4377-9d89-e696ac8746c6.png">
Here it is 😄

**Comment by MystPi** [comment]
Thank you for contributing! 😸  Your build will be added to the releases shortly.

**Comment by MystPi** [comment]
Is it for x64 or x86? Just wondering.

**Comment by webdev03** [comment]
I think it's x86 since my computer has 8gb of RAM

**Comment by MystPi** [comment]
> I think it's x86 since my computer has 8gb of RAM wait why's the zip file called x64? hmm

The amount of ram you have has nothing to do with your architecture.
https://apple.stackexchange.com/questions/12666/how-to-check-whether-my-intel-based-mac-is-32-bit-or-64-bit#:~:text=Go%20to%20the%20Apple%20Menu,have%20a%2064%2Dbit%20CPU.

**Comment by webdev03** [comment]
OK, I think it will be 64 bit then, I think 32 bit is long gone now and I got this computer very recently

**Comment by MystPi** [comment]
> OK, I think it will be 64 bit then, I think 32 bit is long gone now and I got this computer 2020

Okay, thanks for the info!
