### ISSUE TITLE
[discuss] Possible move to jQuery.

### ISSUE THREAD

**Issue by MystPi** [MystPi/ninetails#62]
The jquery branch has already been transferred to jQuery. I also added docstrings, and am probably going to separate `browser.js` into four different files: `global.js`, `functions.js`, `listeners.js`, and `startup.js`.

Is this okay with everyone? Are there any changes you would like to be made? It would also be much appreciated if you could test the jquery branch on your machine for bugs.

**Comment by JaydenDev** [comment]
Your code is hard enough to comprehend as it is, more files that have some kind of meaning I don't know makes it worse.

**Comment by MystPi** [comment]
> Your code is hard enough to comprehend as it is, more files that have some kind of meaning I don't know makes it worse.

It should actually make it easier to understand, as the files are grouped by what they do. Eg. the `functions.js` contains all of the functions, and the `globals.js` file contains all of the global variables.

**Comment by JaydenDev** [comment]
Well, sure I suppose but it all being in one file is always better

**Comment by MystPi** [comment]
> Well, sure I suppose but it all being in one file is always better

Definitely *not* "always" better. If you have a very small project it makes sense to have it all in one file, otherwise everyone is usually better off with multiple files, because it increases readability and modularity.

**Comment by webdev03** [comment]
i heard jquery is old

**Comment by dnlnrs** [comment]
Why jQuery? I don't think it will add value, You can do DOM manipulation without relying on it.
Are you facing some particular issue in the code?

**Comment by MystPi** [comment]
> Why jQuery? I don't think it will add value, You can do DOM manipulation without relying on it. Are you facing some particular issue in the code?

Mostly because of the animations, but I guess you're right; it doesn't really add value to the code.

**Comment by MystPi** [comment]
I'm still going with the code-splitting, though.
