### ISSUE TITLE
Webview Dom Error

### ISSUE THREAD

**Issue by ninjamar** [MystPi/ninetails#66]
Whenever I run ninetails, the console says 
```
Uncaught (in promise) Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at HTMLElement.getWebContentsId (node:electron/js2c/isolated_bundle:17)
    at HTMLElement.e.<computed> [as getURL] (node:electron/js2c/isolated_bundle:21)
    at switchTabs (functions.js:36)
    at createTab (functions.js:94)
    at startup.js:13
```
![](https://ninjamar.dev/assets/images/ninetails-error.png)
Also, new tabs are blank

**Comment by ninjamar** [comment]
I can't do the extensions till this is fixed because the extension code doesn't run. If we use `webview.insertCSS` and `webview.executeJavaScript`, we have to bypass cors. My solution would be to make a cors proxy in node and run it when electron starts.

**Comment by MystPi** [comment]
I'm aware of this issue, but I'm not sure what's causing it. I'll try to find a fix.

**Comment by ninjamar** [comment]
I tried to fix it but I was confused since I thought the webview was already on the page. Maybe it has to do how the variable was set (`document.createElement` vs `document.getElementById`)?

**Comment by MystPi** [comment]
Pushed my fix to the v2.2.4 branch. I was just using `getTitle` before the webview was ready.

**Comment by hello-smile6** [comment]
> I can't do the extensions till this is fixed because the extension code doesn't run. If we use `webview.insertCSS` and `webview.executeJavaScript`, we have to bypass cors. My solution would be to make a cors proxy in node and run it when electron starts.

I'll deploy a cors-anywhere instance on replit.

**Comment by MystPi** [comment]
> > I can't do the extensions till this is fixed because the extension code doesn't run. If we use `webview.insertCSS` and `webview.executeJavaScript`, we have to bypass cors. My solution would be to make a cors proxy in node and run it when electron starts.
> 
> I'll deploy a cors-anywhere instance on replit.

Or use [allOrigins](https://github.com/gnuns/allorigins)

**Comment by hello-smile6** [comment]
Already set it up. See <a href="https://replit.com/@9pfs/cors-anywhere?v=1">`9pfs/cors-anywhere`</a>

**Comment by hello-smile6** [comment]
Use that for right now, I got another idea for a permanent solution.

**Comment by ninjamar** [comment]
> > I can't do the extensions till this is fixed because the extension code doesn't run. If we use `webview.insertCSS` and `webview.executeJavaScript`, we have to bypass cors. My solution would be to make a cors proxy in node and run it when electron starts.

should it be pinged once ninetails loads?

**Comment by MystPi** [comment]
Please discuss CORS and other unrelated topics in a different issue.
