### ISSUE TITLE
Idea: Auto updating

### ISSUE THREAD

**Issue by webdev03** [MystPi/ninetails#8]
There could be a way to automatically update Ninetails. I think that you can use https://www.electronjs.org/docs/latest/api/auto-updater/ or maybe you can fetch from Github API to see if a new release is out.

I can work on the Github API one if you want.

**Comment by MystPi** [comment]
I think the Electron API version would work the best, since it is, of course, part of Electron. I can assign you if you want. 😸

**Comment by webdev03** [comment]
Okay, I can try, but I have a mac so that might be a bit complicated in testing...

**Comment by MystPi** [comment]
> Okay, I can try, but I have a mac so that might be a bit complicated in testing... wait can you ask someone with a mac if my release is signed or not? If it is signed, then epic lol

I don't know anyone *to* ask. Maybe @Chiroyce on Scratch?

**Comment by webdev03** [comment]
Hmm ok...

**Comment by webdev03** [comment]
I don't think it is signed, maybe it doesn't give a warning since I made the file or something?
I'd say to use the GitHub Releases one, I can help with that but I don't know Tailwind.

**Comment by MystPi** [comment]
Sorry for my negligence, but why does Ninetails have to be signed for it to auto-update?

**Comment by webdev03** [comment]
It's a thing with macOS

**Comment by MystPi** [comment]
Oh, okay. I don't use a Mac, so you might be the only one who can figure this out. 😖

**Comment by webdev03** [comment]
I can't spend 100 dollars.. but https://api.github.com/repos/MystPi/ninetails/releases can be used to detect a new release...

**Comment by MystPi** [comment]
I don't really care about auto-updating Ninetails, though it does seem to be a common suggestion. While it would be useful, I don't really wan't to spend a lot of time implementing it.

If anyone else wants to try their hand at it, by all means, feel free to! 😸

**Comment by webdev03** [comment]
Ok, I can try!

**Comment by webdev03** [comment]
I've made a working version (it doesn't reinstall ninetails but it can alert the user) but I do have one question, it does fetch from the Github servers, could that be a privacy breach @MystPi? Also, for my one to work the tag name in the release needs to be the same as `name` in `package.json` but the tag name can have a "v" at the start, so for Ninetails 3:
package.json
```json
{
  "version": "3.0.0"
}
```
release Tag name is `v3.0.0`

**Comment by MystPi** [comment]
> could that be a privacy breach @MystPi?

I don't think so, as anyone can fetch data from the API.

**Comment by webdev03** [comment]
Oh yes I used it

**Comment by MystPi** [comment]
> Oh yes I used it

Okay, just wondering.

I can make an alert for new releases if you want, so you don't have to. I'm also pretty good at styling with Tailwind. 🤣

**Comment by webdev03** [comment]
I made it with Electron by the way, a native popup

**Comment by MystPi** [comment]
> I made it with Electron by the way, a native popup, I added `cross-fetch` so I don't need to use CORS proxy (I don't know if Github uses CORS)

You don't need a CORS proxy for the GitHub API.

**Comment by webdev03** [comment]
Oh, so I could do it in the renderer all along. But I know you will work on it soon.

**Comment by MystPi** [comment]
Finished in #19. Enjoy! 😸

**Comment by webdev03** [comment]
😃

**Comment by webdev03** [comment]
https://github.com/MystPi/ninetails/projects/1#card-74639701  should be done

**Comment by MystPi** [comment]
I just found this out! https://github.com/electron/update.electronjs.org It should auto update the app if I figure out how to implement it.

**Comment by webdev03** [comment]
Wow nice!
