### ISSUE TITLE
Use ionic vue so you can support mobile

### ISSUE THREAD

**Issue by FunctionalMetatable** [MystPi/ninetails#81]
https://ionicframework.com/docs/vue/overview

**Comment by MystPi** [comment]
Does ionic vue support webviews?

**Comment by hello-smile6** [comment]
> Does ionic vue support webviews?

I don't know.

**Comment by hello-smile6** [comment]
> Does ionic vue support webviews?

Probably not.

**Comment by webdev03** [comment]
Capacitor might also work for a plan HTML thing just like Ninetails.

**Comment by FunctionalMetatable** [comment]
It looks like webviews as a ionic component works, but you need to use the html webview element in electron ~ https://ionicframework.com/docs/core-concepts/webview

**Comment by MystPi** [comment]
Eh, the mobile version is pretty much dead. I think I'll be focusing mostly on the desktop app.
