### ISSUE TITLE
Chrome using the js api window.open does not work

### ISSUE THREAD

**Issue by torbjornljung** [MystPi/ninetails#86]
Hi ! 
I'm using the JS API window.open(url, windowName, [windowFeatures]); 
I've used it for years in Windows Internet Explorer. Now Microsoft Edge does not support it, nor does Chrome, I can run it in Edge using IE-Explorer mode for 30 days. 
I really would like to be able to run it in Chrome and skip Microsoft browsers. 
My request looks as this: 
newpath=z:\\books\documentary\(doc)1972 summary(1985) 
window.open(newpath, 'explorer');
(drive z is within my local intranet.) 
But when I try do access it from Chrome, nothing happens at all. Do you know why ? Or if you know how to solve it differently ?
Cheers, Torbjorn, Stockholm, Sweden

**Comment by hello-smile6** [comment]
> Hi ! I'm using the JS API window.open(url, windowName, [windowFeatures]); I've used it for years in Windows Internet Explorer. Now Microsoft Edge does not support it, nor does Chrome, I can run it in Edge using IE-Explorer mode for 30 days. I really would like to be able to run it in Chrome and skip Microsoft browsers. My request looks as this: newpath=z:\books\documentary(doc)1972 summary(1985) window.open(newpath, 'explorer'); (drive z is within my local intranet.) But when I try do access it from Chrome, nothing happens at all. Do you know why ? Or if you know how to solve it differently ? Cheers, Torbjorn, Stockholm, Sweden

Not possible to make it work. Also, off-topic. @MystPi Close as off-topic and lock?
