### ISSUE TITLE
RE: @hello-smile6  status?

### ISSUE THREAD

**Issue by hello-smile6** [MystPi/ninetails#92]
@hello-smile6  status?

_Originally posted by @ninjamar in https://github.com/MystPi/ninetails/issues/50#issuecomment-1005974799_

Haven't gotten to it. Can't reply on original issue, @webdev03 blocked me.

**Comment by MystPi** [comment]
Please don't use issues for replying.

**Comment by hello-smile6** [comment]
> Please don't use issues for replying.

I can't reply on the original one, sorry.

**Comment by MystPi** [comment]
> > Please don't use issues for replying.
> 
> I can't reply on the original one, sorry.

It's okay, it could just clutter the issues tab. Also why did they block you?

**Comment by hello-smile6** [comment]
> > > Please don't use issues for replying.
> > 
> > 
> > I can't reply on the original one, sorry.
> 
> It's okay, it could just clutter the issues tab. Also why did they block you?

Because they didn't like the fact that my Freecat rickroll used the keybindings it did. They are worried that I'd try to do another, even though I'm not going to.

**Comment by MystPi** [comment]
> > > > Please don't use issues for replying.
> > > 
> > > 
> > > I can't reply on the original one, sorry.
> > 
> > 
> > It's okay, it could just clutter the issues tab. Also why did they block you?
> 
> Because they didn't like the fact that my Freecat rickroll used the keybindings it did. They are worried that I'd try to do another, even though I'm not going to.

You also did it to Ninetails -- why? If you thought it was funny, nobody else did.

**Comment by hello-smile6** [comment]
> > > > > Please don't use issues for replying.
> > > > 
> > > > 
> > > > I can't reply on the original one, sorry.
> > > 
> > > 
> > > It's okay, it could just clutter the issues tab. Also why did they block you?
> > 
> > 
> > Because they didn't like the fact that my Freecat rickroll used the keybindings it did. They are worried that I'd try to do another, even though I'm not going to.
> 
> You also did it to Ninetails -- why? If you thought it was funny, nobody else did.

Sorry.

**Comment by ninjamar** [comment]
can u get to it plz?

**Comment by webdev03** [comment]
@hello-smile6 I blocked you because you were trying to be annoying
and also your rickrolls which are not deserved by the open source community

**Comment by hello-smile6** [comment]
> @hello-smile6 I blocked you because you were being annoying and also your rickrolls which are not deserved by the open source community

Sorry

**Comment by ninjamar** [comment]
status?
